### ISSUE TITLE
Can't convert version 3.0+ emoji

### ISSUE THREAD

**Issue by mkaemmerer** [swiftype/slack-hawk-down#5]
The unicode consortium added a bunch of new emoji to the standard. You can find them [here](http://unicode.org/Public/emoji/5.0/emoji-data.txt).

It would be nice to add these to slack-hawk-down so that things like `escapeForSlack(':rolling_on_the_floor_laughing:')` work properly.

**Comment by alechoey** [comment]
Closed by #7
